### ISSUE TITLE
alignment.py doesnt work

### ISSUE THREAD

**Issue by jujemu** [stylegan-human/StyleGAN-Human#30]
run:  
`!python alignment.py --image-folder /content/input --output-folder /content/output.` ,  

but I got  
```
Traceback (most recent call last):
  File "alignment.py", line 221, in <module>
    run(cmd_args)
  File "alignment.py", line 144, in run
    comb, segmentation, bg, ori_img = human_seg.run(image,None)  #mybg) 
  File "/content/StyleGAN-Human/PP_HumanSeg/deploy/infer.py", line 100, in run
    processed_imgs, ori_shapes = self.preprocess(img)
  File "/content/StyleGAN-Human/PP_HumanSeg/deploy/infer.py", line 92, in preprocess
    processed_img = self.compose(img)[0]
  File "/usr/local/lib/python3.7/dist-packages/paddleseg/transforms/transforms.py", line 56, in __call__
    if 'img' not in data.keys():
AttributeError: 'numpy.ndarray' object has no attribute 'keys'
```
# My environment
 - colab pro. 
 - input folder: /content/input; only one image, of which size is `(512, 1024)`, PIL image.
 - To solve module error, `!pip install paddleseg paddlepaddle`

and I believe, the problem is  [here](https://github.com/stylegan-human/StyleGAN-Human/blob/811a8ead359b2b5d7c63a71cfc53621a9a907eb9/PP_HumanSeg/deploy/infer.py#L71), `self.compose = T.Compose(self.cfg.transforms)`.  
self.cfg.transforms wants to get dictionary having a key, 'img'.  
but I cant get though it.

Plz help.

**Comment by xjdeng** [comment]
Same here, I'm having this issue as well.  Are we supposed to try older versions of paddleseg?  I might do that and report back if it solves it.

**Comment by Lakshmanaraja** [comment]
same error coming. 3 months back when the alignment code was released , It was working perfectly fine. Is there any version mismatch? 

  File "alignment.py", line 221, in <module>
    run(cmd_args)
  File "alignment.py", line 144, in run
    comb, segmentation, bg, ori_img = human_seg.run(image,None)  #mybg) 
  File "/content/StyleGAN-Human/PP_HumanSeg/deploy/infer.py", line 100, in run
    processed_imgs, ori_shapes = self.preprocess(img)
  File "/content/StyleGAN-Human/PP_HumanSeg/deploy/infer.py", line 92, in preprocess
    processed_img = self.compose(img)[0]
  File "/usr/local/lib/python3.7/dist-packages/paddleseg/transforms/transforms.py", line 56, in __call__
    if 'img' not in data.keys():
AttributeError: 'numpy.ndarray' object has no attribute 'keys'

**Comment by xjdeng** [comment]
I got it to work by downgrading paddleseg to version 2.5

**Comment by jujemu** [comment]
I didnt check that it works, @xjdeng I believe, then it can close.

**Comment by MisunJoo** [comment]
`python -m pip install paddlepaddle-gpu==2.5.2.post120 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html `

works for me

**Comment by MisunJoo** [comment]
after I downgraded, I did https://github.com/PaddlePaddle/PaddleDetection/issues/7629#issuecomment-1580240895
then it works
