### ISSUE TITLE
Fine-Tuning with original data

### ISSUE THREAD

**Issue by ccc07130** [stylegan-human/StyleGAN-Human#38]
I'm trying to additionally train a model for StyleGAN3 using my own images (512x512 resolution).
```
python train.py --outdir=training_results/sg3/ --cfg=stylegan3-r --gpus=8 --batch=32 --gamma=12.4 \
    --mirror=1 --aug=noaug --data=data/OrgData/ --square=True --snap=250
```

When I run the prepared script, I get the following error:
```
Traceback (most recent call last):
  File "train_stylegan_human.py", line 293, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "train_stylegan_human.py", line 288, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train_stylegan_human.py", line 98, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train_stylegan_human.py", line 49, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/home/rd/img_studio/source/submodules/StyleGAN3/training/training_loop.py", line 163, in training_loop
    misc.copy_params_and_buffers(resume_data[name], module, require_all=False)
  File "/home/rd/img_studio/source/submodules/StyleGAN3/torch_utils/misc.py", line 164, in copy_params_and_buffers
    tensor.copy_(src_tensors[name].detach()).requires_grad_(tensor.requires_grad)
RuntimeError: The size of tensor a (512) must match the size of tensor b (1024) at non-singleton dimension 1
```

I set _--cbase=16384_ referring to the StyleGAN3 issue, but the result did not change.

Can someone please tell me how to deal with this?

**Comment by Neilstid** [comment]
I'm facing the same issue, how did you solve it ? Which param to modify ?
